In [8]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [15]:
sentences = ["Ala ma kota", "Ala posiada kota", "Krzysiu ma psa", "Ala ma psa"]


In [21]:
embedding_1= model.encode(sentences[0], convert_to_tensor=True)
embedding_2 = model.encode(sentences[1], convert_to_tensor=True)
embedding_3 = model.encode(sentences[2], convert_to_tensor=True)
embedding_4 = model.encode(sentences[3], convert_to_tensor=True)
embedding_1.shape


torch.Size([384])

In [17]:
util.pytorch_cos_sim(embedding_1, embedding_2)

tensor([[0.7428]])

In [18]:
util.pytorch_cos_sim(embedding_1, embedding_3)

tensor([[0.3569]])

In [19]:
util.pytorch_cos_sim(embedding_1, embedding_4)

tensor([[0.5411]])